//VScodeの REST Client拡張機能を使ってリクエストの動作確認するためのファイルです．
//GET http://localhost:5000/Una

POST http://localhost:5001/postcards HTTP/1.1
Content-Type: application/json

# {
#     "num": 1000000,
#     "useCards" :[
#         1,1,1,1,1
#     ]
# }

{
    "num": 1000000,
    "useCards":[
        0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51
    ]
}


# useCards の仕様
# 52枚のトランプカードに0~51の番号が割り振られています．
# 番号の割り振りは，例えばスペード，ハート，クラブ，ダイヤの順の場合，
# 0~12  がスペードの1~12,
# 13~25 がハートの1~12,
# 26~38 がクラブの1~12,
# 39~51 がダイヤの1~12, といったようになっています．
# 記号の順に制約はありません．

# POSTリクエストで送るuseCardsには，この番号の配列を詰めます．
# 番号はどのように並んでいてもに制約はありません．
# 重複さえ無ければ問題ありません
# 重複チェックもバックエンド側に追加するかも